{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(api_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Интенсивность",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доля Ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(api_errors_total[5m])) / sum(rate(api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}